export const AllUrls = [
  { url: "/dashboard", name: "dashboard" },
  { url: "/profile", name: "profile" },
  { url: "/AssignSchool", name: "assign school" },
  { url: "/star-attendance", name: "star attendance" },
  { url: "/NoteList", name: "notes" },
  { url: "/NoteBook-List", name: "noteBook" },
  { url: "/StarReward", name: "star reward" },
  { url: "/thisWeek", name: "week plan" },
  { url: "/role-deligated", name: "role deligation" },
  { url: "/Assignment/awarenessCourses", name: "assignment awarness" },
  { url: "/Assignment/worksheet", name: "assignment worksheet" },
  { url: "/Assignment/assessment", name: "assignment assessment" },
  { url: "/Assignment/lab", name: "assignment lab" },
  { url: "/elibrary/awarenessCourses", name: "elibrary awarness" },
  { url: "/elibrary/worksheet", name: "elibrary worksheet" },
  { url: "/elibrary/assessment", name: "elibrary assessment" },
  { url: "/elibrary/lab", name: "elibrary lab" },
  { url: "/ShopList", name: "shop" },
  { url: "/schedule-meetings", name: "schedule meeting" },
  { url: "/examTimetable", name: "exam time table" },
  { url: "/task-reminders", name: "task reminder" },
  { url: "/complaints-report", name: "complain report" },
  { url: "/help-feedback", name: "help feedback" },
  { url: "/Lost-Found", name: "lost found" },

  { url: "/wallet", name: "wallet" },
  { url: "/transportationList", name: "transportation" },
  { url: "/leave-request", name: "leave request" },
  { url: "/early-leave-list", name: "early leave request" },
  { url: "/performance", name: "performance" },
  { url: "/profile-attendance-all", name: "profile attendance" },
  { url: "/ClassScheduleNew", name: "class schedule" },
  { url: "/profilecardstags", name: "cards & tags" },
  //   { url: "/profilecardstags", name: "cards tags" },
  { url: "/medicalsurvey", name: "medical survey" },
  { url: "/annual-schedule", name: "annual schedule" },
  { url: "/my-location-list", name: "location" },
  { url: "/settings", name: "notification setting" },
];
